# Generated by Django 4.0.2 on 2022-02-16 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='documents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doc_name', models.CharField(max_length=10)),
                ('fol_id', models.IntegerField(max_length=10)),
                ('top_id', models.IntegerField(max_length=10)),
                ('doc_id', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='employee',
        ),
    ]
