# Generated by Django 4.0.2 on 2022-02-16 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapp', '0002_documents_delete_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='folders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fol_name', models.CharField(max_length=10)),
                ('fol_id', models.IntegerField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='topics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_name', models.CharField(max_length=10)),
                ('top_id', models.IntegerField(max_length=10)),
            ],
        ),
    ]
