# Generated by Django 4.0.2 on 2022-02-24 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weapp', '0003_folders_topics'),
    ]

    operations = [
        migrations.DeleteModel(
            name='folders',
        ),
        migrations.DeleteModel(
            name='topics',
        ),
        migrations.RenameField(
            model_name='documents',
            old_name='fol_id',
            new_name='fol_name',
        ),
        migrations.RenameField(
            model_name='documents',
            old_name='top_id',
            new_name='top_name',
        ),
    ]
