# Generated by Django 4.0.2 on 2022-02-24 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weapp', '0004_delete_folders_delete_topics_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documents',
            name='doc_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documents',
            name='fol_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='documents',
            name='top_name',
            field=models.CharField(max_length=50),
        ),
    ]
